services:
  catalog:
    build: ./catalog
    expose:
    - "80"
    ports:
    - "80:80"
    volumes:
    - ./Catalog/catalog.json:/app/catalog.json

  node-red:
    build: ./Node-RED
    ports:
      - "8082:8082"
    depends_on: 
      - catalog    
    links:
      - catalog
  security:
    build: ./Security
    expose:
      - "30"
    ports:
      - "30:30" 
    depends_on:
      - catalog 

  nodered-dashboard:
    image: nodered/node-red
    container_name: Node-REDdashboard
    ports:
      - "1880:1880"
    restart: unless-stopped 
    volumes:
    - ./Node-REDdashboard:/data

  thingspeak_adaptor:
    build: ./ThingSpeak Adaptor  
    expose:
      - "9090"
    ports:
      - "9090:9090" 
    depends_on:
      - catalog  
    links:
      - catalog 

  threshold_management:
    build: ./Threshold Management 
    expose:
      - "8081"
    ports:
      - "8081:8081"  
    depends_on:
      - catalog  
      - thingspeak_adaptor  
    links:
      - catalog 
      - thingspeak_adaptor  

  lighting_control:
    build: ./Lighting Control  
    expose:
      - "9091"
    ports:
      - "9091:9091" 
    depends_on:
      - catalog  
    links:
      - catalog 
  
  pump_control:
    build: ./Pump Control 
    expose:
      - "9092"
    ports:
      - "9092:9092" 
    depends_on:
      - catalog  
    links:
      - catalog 

  temperature_control:
    build: ./Temperature Control 
    expose:
      - "9093"
    ports:
      - "9093:9093" 
    depends_on:
      - catalog  
    links:
      - catalog 

  other_device_connector:
    build: ./Other Device Connector 
    expose:
      - "9094"
    ports:
      - "9094:9094" 
    depends_on:
      - catalog  
    links:
      - catalog 

  raspberry_device_connector:
    build: ./Raspberry PI Connector 
    expose:
      - "9095"
    ports:
      - "9095:9095" 
    depends_on:
      - catalog  
    links:
      - catalog 

  #telegram_bot:
    #build: ./Telegram_Bot 
    #expose:
      #- "9096"
    #ports:
      #- "9096:9096" 
    #depends_on:
     # - catalog  
    #links:
      #- catalog 
